apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-config
  namespace: notification-service
data:
  kafka-brokers: "redpanda.notification-service.svc.cluster.local:9092"
  delivery-service-url: "http://delivery-service.notification-service.svc.cluster.local:50051"
